#!/bin/bash

blog_path=YOUR_BLOG_DIR
rsa_path=~/.ssh/id_rsa
handle_user=node


if [ $1 = 'server' ];then 
	docker run --rm --name hexo_server -v ${rsa_path}:/tmp/hexo_config/id_rsa:ro -v $PWD/.gitconfig:/tmp/hexo_config/.gitconfig  -v ${blog_path}:/tmp/blog/ -u ${handle_user} -w /tmp/blog -p 4000:4000 -d myhexo $@
else
	docker run --rm -v ${rsa_path}:/tmp/hexo_config/id_rsa:ro -v $PWD/.gitconfig:/tmp/hexo_config/.gitconfig  -v ${blog_path}:/tmp/blog/ -u ${handle_user} -w /tmp/blog myhexo $@
fi
